<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework />
    <TargetFrameworks>net48;netstandard2.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../AdNoctem.Substrate.Diagnostics/AdNoctem.Substrate.Diagnostics.csproj" />
    <ProjectReference Include="../AdNoctem.Substrate.Registry/AdNoctem.Substrate.Registry.csproj" />
    <ProjectReference Include="../AdNoctem.Substrate.Windows/AdNoctem.Substrate.Windows.csproj" />
    <ProjectReference Include="../AdNoctem.Substrate.Security/AdNoctem.Substrate.Security.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net48'">
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Runtime.Serialization" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>
</Project>
