<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework />
    <TargetFrameworks>net48;netstandard2.0</TargetFrameworks>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="PowerShellStandard.Library" Version="5.1.1" PrivateAssets="all" ExcludeAssets="runtime" />
    <ProjectReference Include="../AdNoctem.Substrate.Core/AdNoctem.Substrate.Core.csproj" />
    <ProjectReference Include="../AdNoctem.Substrate.Office/AdNoctem.Substrate.Office.csproj" />
    <ProjectReference Include="../AdNoctem.Substrate.Security/AdNoctem.Substrate.Security.csproj" />
    <ProjectReference Include="../AdNoctem.Substrate.Packages/AdNoctem.Substrate.Packages.csproj" />
    <ProjectReference Include="../AdNoctem.Substrate.Windows/AdNoctem.Substrate.Windows.csproj" />
    <ProjectReference Include="../AdNoctem.Substrate.Interop/AdNoctem.Substrate.Interop.csproj" />
    <ProjectReference Include="../AdNoctem.Substrate.Diagnostics/AdNoctem.Substrate.Diagnostics.csproj" />
    <ProjectReference Include="../AdNoctem.Substrate.IO/AdNoctem.Substrate.IO.csproj" />
    <ProjectReference Include="../AdNoctem.Substrate.Policies/AdNoctem.Substrate.Policies.csproj" />
    <ProjectReference Include="../AdNoctem.Substrate.Networking/AdNoctem.Substrate.Networking.csproj" />
    <ProjectReference Include="../AdNoctem.Substrate.Registry/AdNoctem.Substrate.Registry.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net48'">
    <Reference Include="System.Net.Http" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>
</Project>
