name: Release

on:
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    shell: pwsh

concurrency:
  group: "release-${{ github.ref }}"

jobs:
  release:
    if: ${{ vars.PSFOUNDATION_RELEASE_ENABLED == 'true' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/next') }}
    runs-on: windows-2022
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d # v5.0.0
        with:
          global-json-file: global.json
      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2
        with:
          bun-version: 1.4.2
      - name: Restore
        run: dotnet msbuild tools/tasks.proj -t:Restore
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@b12c8f6015dc215fe37bc154d4ad456dd3833c90 # v6.0.0
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.ANC_GITHUB_TOKEN }}
        with:
          semantic_version: 25
          extra_plugins: |
            @semantic-release/changelog@6.0.3
            @semantic-release/exec@7.0.3
            @semantic-release/git@10.0.1
            conventional-changelog-conventionalcommits@8.0.0
      - name: Publish validated package
        if: steps.semantic.outputs.new_release_published == 'true'
        env:
          PSF_RELEASE_VERSION: ${{ steps.semantic.outputs.new_release_version }}
          NUGET_API_KEY: ${{ secrets.PSGALLERY_TOKEN }}
        run: ./tools/release.ps1 -Publish -Version $env:PSF_RELEASE_VERSION
