<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Compile Include="../fixtures/v2/OutlookFixture.cs" Link="OutlookFixture.cs" />
    <ProjectReference Include="../../src/PSFoundation.Windows/PSFoundation.Windows.csproj" />
    <ProjectReference Include="../../src/PSFoundation.Interop/PSFoundation.Interop.csproj" />
  </ItemGroup>
</Project>
